# Stage 1: Build the Angular app
FROM node:latest as build

WORKDIR /usr/app

COPY ./ /usr/app/

RUN npm install

RUN npm run build

# Stage 2: Create a minimal Nginx image and copy the built Angular app
FROM nginx:latest

COPY --from=build /usr/app/dist/swe642surveys-ui /usr/share/nginx/html
COPY /nginx-custom.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
